site_name: bulletty
site_url: https://bulletty.croci.dev/
repo_url: https://github.com/CrociDB/bulletty
repo_name: CrociDB/bulletty
theme:
  name: material
  features:
      - navigation.tabs
  icon:
      logo: material/rss-box
  palette:
    scheme: slate
    primary: black
    accent: amber
  show_title: true
  show_stargazers: true
  font:
    text: Roboto

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - codehilite
  - admonition

nav:
  - Getting Started:
    - bulletty: 'index.md'
    - Install: 'install.md'
    - Contributing: 'contributing.md'
  - Docs:
    - CLI Reference: 'docs/cli_reference.md'
    - Themes: 'docs/themes.md'
    - Reference: 'docs/reference.md'
