scheme = "GitHub Dark Dimmed"
author = "Juan David Merchan Torres (NikolaM-Dev)"
base00 = "1e232a"
base01 = "1e232a"
base02 = "212830"
base03 = "545d68"
base04 = "768390"
base05 = "adbac7"
base06 = "adbac7"
base07 = "00ff00"
base08 = "539bf5"
base09 = "f69d50"
base0A = "00ff00"
base0B = "00ff00"
base0C = "8ddb8c"
base0D = "bc7cff"
base0E = "00ff00"
base0F = "00ff00"
